# VeriAudit - Report MCP Server
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List

from veriaudit.core.schema import Finding, ProjectProfile, AuditReport
from veriaudit.mcp_servers.base_mcp import BaseMCP


class ReportMCP(BaseMCP):
    """MCP server for report generation in HTML, JSON, Markdown, and SARIF formats."""

    @property
    def server_name(self) -> str:
        return "report_mcp"

    def generate_markdown_report(self, findings: List[Dict], profile: Dict,
                                  events: List[Dict] = None,
                                  output_dir: str = "./results") -> dict:
        """Generate a Markdown audit report."""
        report_path = os.path.join(output_dir, "report.md")
        os.makedirs(output_dir, exist_ok=True)

        # Count by status
        status_counts = {}
        for f in findings:
            s = f.get("status", "raw")
            status_counts[s] = status_counts.get(s, 0) + 1

        confirmed = [f for f in findings if f.get("status") == "confirmed_exploited"]
        total = len(findings)

        md = f"""# VeriAudit Security Audit Report

## Project Information
- **Repository**: {profile.get('repo_url', 'N/A')}
- **Commit**: {profile.get('commit_sha', 'N/A')}
- **Language**: {profile.get('language', 'unknown')}
- **Build System**: {profile.get('build_system', 'unknown')}
- **Audit Date**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}

---

## Executive Summary

| Metric | Count |
|--------|-------|
| Total RAW findings | {status_counts.get('raw', 0)} |
| Candidates | {status_counts.get('candidate', 0)} |
| Reachable | {status_counts.get('reachable', 0)} |
| Exploitable | {status_counts.get('exploitable', 0)} |
| **Confirmed Exploited** | **{status_counts.get('confirmed_exploited', 0)}** |
| Rejected | {status_counts.get('rejected', 0)} |
| Unreproducible | {status_counts.get('unreproducible', 0)} |
| False Positives | {status_counts.get('false_positive', 0)} |
| Inconclusive | {status_counts.get('inconclusive', 0)} |

---

## Confirmed Vulnerabilities
"""

        if confirmed:
            for i, f in enumerate(confirmed, 1):
                severity = f.get('severity', 'info').upper()
                cwe = f.get('cwe', 'N/A')
                file_path = f.get('location', {}).get('file', f.get('file_path', 'unknown'))
                line = f.get('location', {}).get('line_start', f.get('line_start', 0))
                message = f.get('message', '')
                ruling_reason = f.get('ruling_reason', '')
                llm_analysis = f.get('llm_analysis', '')

                md += f"""
### {i}. [{severity}] {cwe} — {file_path}:{line}

**Finding ID**: `{f.get('finding_id', '')}`

**Description**: {message}

**Evidence**:
- Source Tool: {f.get('source_tool', 'unknown')}
- Rule: {f.get('rule_id', '')}
- Confidence: {f.get('confidence', 'medium')}

**Ruling**: {ruling_reason}

"""
                if llm_analysis:
                    md += f"**Analysis**: {llm_analysis}\n\n"
        else:
            md += "\n*No confirmed vulnerabilities found.*\n\n"

        # Dynamic verification section
        md += """---
## Dynamic Verification

| Status |
|--------|
| Dynamic verification is reserved but not yet fully implemented. |

> **Note**: All findings above are based on static analysis and LLM-assisted review.
> No exploit confirmation has been performed beyond what is shown in evidence.

---

## Appendix: Rejected & Inconclusive Findings
"""

        rejected = [f for f in findings if f.get("status") in ("rejected", "false_positive", "unreproducible", "inconclusive")]
        if rejected:
            for f in rejected:
                fid = f.get("finding_id", "?")
                st = f.get("status", "?")
                loc = f.get("location", {})
                file_path = loc.get("file", f.get("file_path", "?"))
                line = loc.get("line_start", f.get("line_start", "?"))
                reason = f.get("ruling_reason", f.get("message", ""))
                md += f"- `{fid}` [{st}] {file_path}:{line} — {reason[:120]}\n"

        md += f"""
---
*Report generated by VeriAudit on {datetime.now(timezone.utc).isoformat()}*
"""

        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(md)

        return {"report_path": report_path, "format": "markdown"}

    def generate_html_report(self, findings: List[Dict], profile: Dict,
                              events: List[Dict] = None,
                              output_dir: str = "./results") -> dict:
        """Generate an HTML audit report."""
        report_path = os.path.join(output_dir, "report.html")
        os.makedirs(output_dir, exist_ok=True)

        confirmed = [f for f in findings if f.get("status") == "confirmed_exploited"]
        total = len(findings)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>VeriAudit Report — {profile.get('repo_url', 'Unknown')}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; background: #fff; color: #1a1a1a; }}
h1 {{ border-bottom: 2px solid #2563eb; padding-bottom: .5rem; }}
h2 {{ color: #2563eb; margin-top: 2rem; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ border: 1px solid #e5e7eb; padding: .5rem .75rem; text-align: left; }}
th {{ background: #f9fafb; }}
.severity-CRITICAL {{ background: #fecaca; color: #991b1b; font-weight: bold; }}
.severity-HIGH {{ background: #fed7aa; color: #9a3412; font-weight: bold; }}
.severity-MEDIUM {{ background: #fef08a; color: #854d0e; }}
.finding-card {{ border: 1px solid #e5e7eb; border-radius: .5rem; padding: 1rem; margin: 1rem 0; }}
.evidence-section {{ background: #f3f4f6; padding: .5rem 1rem; border-radius: .25rem; margin-top: .5rem; }}
.warning {{ background: #fef3c7; border-left: 4px solid #f59e0b; padding: 1rem; margin: 1rem 0; }}
</style>
</head>
<body>
<h1>VeriAudit Security Audit Report</h1>

<h2>Project Information</h2>
<table>
<tr><th>Repository</th><td>{profile.get('repo_url', 'N/A')}</td></tr>
<tr><th>Commit</th><td><code>{profile.get('commit_sha', 'N/A')}</code></td></tr>
<tr><th>Language</th><td>{profile.get('language', 'unknown')}</td></tr>
<tr><th>Total Findings</th><td>{total}</td></tr>
<tr><th>Confirmed Exploited</th><td><strong>{len(confirmed)}</strong></td></tr>
</table>

<h2>Confirmed Vulnerabilities ({len(confirmed)})</h2>
"""
        if confirmed:
            for f in confirmed:
                fid = f.get('finding_id', '')
                sev = (f.get('severity', 'info') or 'info').upper()
                cwe = f.get('cwe', 'N/A')
                loc = f.get('location', {})
                file_path = loc.get('file', f.get('file_path', 'unknown'))
                line = loc.get('line_start', f.get('line_start', 0))
                message = f.get('message', '')
                html += f"""
<div class="finding-card severity-{sev}">
  <strong>{cwe}</strong> — <code>{file_path}:{line}</code>
  <p>{message}</p>
  <div class="evidence-section">
    <small>Finding ID: <code>{fid}</code> | Tool: {f.get('source_tool', 'unknown')} | Rule: {f.get('rule_id', '')}</small>
  </div>
</div>"""
        else:
            html += "<p><em>No confirmed vulnerabilities found.</em></p>"

        html += """
<h2>Dynamic Verification</h2>
<div class="warning">
  <strong>⚠ Not Implemented</strong><br>
  Dynamic verification (Fuzz, ASan, OOB callback) is reserved but not yet implemented.
  All findings are based on static analysis only.
</div>

</body>
</html>"""

        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(html)

        return {"report_path": report_path, "format": "html"}

    def generate_json_report(self, findings: List[Dict], profile: Dict,
                              events: List[Dict] = None,
                              output_dir: str = "./results") -> dict:
        """Generate a JSON findings file."""
        report_path = os.path.join(output_dir, "findings.json")
        os.makedirs(output_dir, exist_ok=True)

        data = {
            "project": profile,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "total_findings": len(findings),
            "findings": findings,
        }

        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, default=str, ensure_ascii=False)

        return {"report_path": report_path, "format": "json"}

    def generate_sarif(self, findings: List[Dict], profile: Dict,
                        output_dir: str = "./results") -> dict:
        """Generate a SARIF v2.1.0 report."""
        report_path = os.path.join(output_dir, "findings.sarif")
        os.makedirs(output_dir, exist_ok=True)

        results = []
        for f in findings:
            loc = f.get("location", {})
            results.append({
                "ruleId": f.get("rule_id", "unknown"),
                "level": self._sarif_level(f.get("severity", "info")),
                "message": {"text": f.get("message", "")},
                "locations": [{
                    "physicalLocation": {
                        "artifactLocation": {
                            "uri": loc.get("file", f.get("file_path", "unknown")),
                        },
                        "region": {
                            "startLine": loc.get("line_start", f.get("line_start", 1)),
                        },
                    },
                }],
            })

        sarif = {
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [{
                "tool": {
                    "driver": {
                        "name": "VeriAudit",
                        "informationUri": "https://github.com/Happyhppay/VeriAudit",
                    },
                },
                "results": results,
            }],
        }

        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(sarif, f, indent=2, default=str, ensure_ascii=False)

        return {"sarif_path": report_path, "format": "sarif"}

    def generate_batch_summary(self, project_results: List[Dict],
                                output_dir: str = "./results") -> dict:
        """Generate a batch summary across multiple projects."""
        summary_path = os.path.join(output_dir, "batch_summary.md")
        os.makedirs(output_dir, exist_ok=True)

        md = "# VeriAudit Batch Audit Summary\n\n"
        md += "| Project | Language | RAW | Confirmed | Rejected | Duration |\n"
        md += "|---------|----------|-----|-----------|----------|----------|\n"

        for r in project_results:
            profile = r.get("profile", {})
            findings = r.get("findings", [])
            name = profile.get("repo_url", "?").split("/")[-1].replace(".git", "")
            lang = profile.get("language", "?")
            total = len(findings)
            confirmed = sum(1 for f in findings if f.get("status") == "confirmed_exploited")
            rejected = sum(1 for f in findings if f.get("status") in ("rejected", "false_positive"))
            dur = r.get("duration_seconds", 0)

            md += f"| {name} | {lang} | {total} | {confirmed} | {rejected} | {self._fmt_dur(dur)} |\n"

        with open(summary_path, 'w', encoding='utf-8') as f:
            f.write(md)

        return {"summary_path": summary_path}

    def _sarif_level(self, severity: str) -> str:
        m = {"critical": "error", "high": "error", "medium": "warning",
             "low": "note", "info": "note"}
        return m.get(severity.lower(), "warning")

    def _fmt_dur(self, seconds: float) -> str:
        if seconds < 60:
            return f"{seconds:.0f}s"
        elif seconds < 3600:
            return f"{seconds/60:.1f}m"
        return f"{seconds/3600:.1f}h"

    # ==================== Tool Schemas ====================

    def get_tool_schemas(self) -> List[Dict[str, Any]]:
        return [
            {"name": f"{self.server_name}.generate_markdown_report",
             "description": "Generate a Markdown audit report",
             "parameters": {"type": "object", "properties": {"findings": {"type": "array"}, "profile": {"type": "object"}, "events": {"type": "array"}, "output_dir": {"type": "string"}}, "required": ["findings", "profile", "output_dir"]}},
            {"name": f"{self.server_name}.generate_html_report",
             "description": "Generate an HTML audit report",
             "parameters": {"type": "object", "properties": {"findings": {"type": "array"}, "profile": {"type": "object"}, "events": {"type": "array"}, "output_dir": {"type": "string"}}, "required": ["findings", "profile", "output_dir"]}},
            {"name": f"{self.server_name}.generate_json_report",
             "description": "Generate a JSON findings file",
             "parameters": {"type": "object", "properties": {"findings": {"type": "array"}, "profile": {"type": "object"}, "events": {"type": "array"}, "output_dir": {"type": "string"}}, "required": ["findings", "profile", "output_dir"]}},
            {"name": f"{self.server_name}.generate_sarif",
             "description": "Generate a SARIF v2.1.0 report",
             "parameters": {"type": "object", "properties": {"findings": {"type": "array"}, "profile": {"type": "object"}, "output_dir": {"type": "string"}}, "required": ["findings", "profile", "output_dir"]}},
            {"name": f"{self.server_name}.generate_batch_summary",
             "description": "Generate batch audit summary across projects",
             "parameters": {"type": "object", "properties": {"project_results": {"type": "array"}, "output_dir": {"type": "string"}}, "required": ["project_results", "output_dir"]}},
        ]
