# VeriAudit - Memory Corruption + Integer Overflow + Format String Handlers
from __future__ import annotations

from typing import Any, Dict, List

from veriaudit.core.schema import Finding, JudgeRule, FindingStatus, SANITIZER_ERROR_PATTERNS

from ..base import VulnerabilityClassHandler


class MemoryCorruptionHandler(VulnerabilityClassHandler):
    """Handler for memory corruption: buffer overflow, OOB read/write, UAF, double-free."""

    @property
    def vuln_class_name(self) -> str:
        return "memory-corruption"

    @property
    def cwe_ids(self) -> List[str]:
        return ["CWE-119", "CWE-120", "CWE-121", "CWE-122",
                "CWE-125", "CWE-787", "CWE-416", "CWE-415", "CWE-476"]

    @property
    def applicable_languages(self) -> List[str]:
        return ["c++", "c", "rust", "go"]

    def get_discovery_rules(self, language: str) -> List[Dict[str, Any]]:
        if language.lower() in ("c++", "c"):
            return [
                {"tool": "codeql", "rule": "cpp/overrunning-write"},
                {"tool": "codeql", "rule": "cpp/overrunning-read"},
                {"tool": "codeql", "rule": "cpp/use-after-free"},
                {"tool": "codeql", "rule": "cpp/double-free"},
                {"tool": "codeql", "rule": "cpp/unbounded-write"},
                {"tool": "semgrep", "rule": "c-memory-unsafe"},
                {"tool": "cppcheck", "rule": "bufferAccessOutOfBounds"},
                {"tool": "cppcheck", "rule": "memleak"},
            ]
        elif language.lower() == "rust":
            return [
                {"tool": "semgrep", "rule": "rust-unsafe-block"},
                {"tool": "codeql", "rule": "rust/unsafe-use"},
            ]
        elif language.lower() == "go":
            return [
                {"tool": "semgrep", "rule": "go-unsafe-pointer"},
                {"tool": "codeql", "rule": "go/unsafe-usage"},
            ]
        return [{"tool": "semgrep", "rule": f"{language.lower()}-memory-unsafe"}]

    def generate_trigger(self, finding: Finding,
                          context: Dict[str, Any]) -> Dict[str, Any]:
        """Memory corruption trigger: fuzz harness + seed corpus."""
        repo_path = context.get("repo_path", "")
        language = context.get("language", "c++").lower()

        # Generate a libFuzzer harness for the target function
        func_name = finding.location.function or "target_function"
        file_path = finding.location.file

        harness_templates = {
            "c++": f'''#include <cstdint>
#include <cstddef>
#include <cstdio>

// Harness for: {func_name} in {file_path}
// Auto-generated by VeriAudit MemoryCorruptionHandler

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {{
    if (size == 0) return 0;
    // TODO: call {func_name} with fuzz data
    // {func_name}(data, size);
    return 0;
}}
''',
        }

        harness_code = harness_templates.get(language, harness_templates["c++"])

        return {
            "trigger_type": "fuzz_harness",
            "vulnerability_type": "memory-corruption",
            "harness_code": harness_code,
            "harness_file": f"/tmp/harness_{finding.finding_id}.cpp",
            "build_command": "clang++ -g -O1 -fsanitize=fuzzer,address -o /tmp/fuzz_target {harness_file}",
            "run_command": "/tmp/fuzz_target -max_total_time=3600 -artifact_prefix=/tmp/crashes/ /tmp/corpus/",
            "corpus_source": f"{repo_path}/test/data" if repo_path else "",
        }

    def verify_dynamically(self, finding: Finding,
                            trigger: Dict[str, Any],
                            context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Dynamic verification for memory corruption.
        Requires: ASan binary, crash input, release binary, debug binary.
        """
        asan_binary = context.get("asan_binary", "")
        release_binary = context.get("release_binary", "")
        debug_binary = context.get("debug_binary", "")
        crash_input = trigger.get("crash_input", "")

        results = {
            "confirmed": False,
            "asan_report": None,
            "release_crashed": False,
            "backtrace": "",
            "stability": {"total_runs": 0, "successful_runs": 0, "rating": "UNTESTED"},
        }

        if not asan_binary or not crash_input:
            return results

        # Run under ASan
        from veriaudit.core.container_pool import ContainerPool
        pool = ContainerPool()
        container_id = context.get("container_id")

        if container_id:
            exit_code, stdout, stderr = pool.exec_cmd(
                container_id,
                f"{asan_binary} {crash_input}",
                timeout=30,
            )
            # Parse ASan output
            for error_type, info in SANITIZER_ERROR_PATTERNS.items():
                if any(kw in stderr for kw in info["keywords"]):
                    results["asan_report"] = error_type
                    results["confirmed"] = True
                    break

        return results

    def get_judge_rules(self) -> List[JudgeRule]:
        return [
            JudgeRule(rule_id="MEM-R001",
                      condition="ASan heap-buffer-overflow WRITE + 10/10 repro",
                      verdict=FindingStatus.CONFIRMED_EXPLOITED, confidence=0.98, priority=1),
            JudgeRule(rule_id="MEM-R002",
                      condition="ASan heap-use-after-free + 10/10 repro",
                      verdict=FindingStatus.CONFIRMED_EXPLOITED, confidence=0.98, priority=1),
            JudgeRule(rule_id="MEM-R003",
                      condition="ASan double-free + 10/10 repro",
                      verdict=FindingStatus.CONFIRMED_EXPLOITED, confidence=0.98, priority=1),
        ]


class IntegerOverflowHandler(VulnerabilityClassHandler):
    """Handler for integer overflow/underflow (CWE-190, CWE-191)."""

    @property
    def vuln_class_name(self) -> str:
        return "integer-overflow"

    @property
    def cwe_ids(self) -> List[str]:
        return ["CWE-190", "CWE-191"]

    @property
    def applicable_languages(self) -> List[str]:
        return ["c++", "c", "rust"]

    def get_discovery_rules(self, language: str) -> List[Dict[str, Any]]:
        return [
            {"tool": "codeql", "rule": "cpp/integer-overflow"},
            {"tool": "cppcheck", "rule": "integerOverflow"},
            {"tool": "semgrep", "rule": "c-integer-overflow"},
        ]

    def generate_trigger(self, finding: Finding,
                          context: Dict[str, Any]) -> Dict[str, Any]:
        # Generate boundary-value corpus for triggering overflow
        boundary_values = [
            0, 1, -1, 127, 128, 255, 256,
            32767, 32768, 65535, 65536,
            2147483647, 2147483648, 4294967295, 4294967296,
        ]
        return {
            "trigger_type": "boundary_corpus",
            "vulnerability_type": "integer-overflow",
            "boundary_values": boundary_values,
            "ubsan_flags": "-fsanitize=undefined -fno-omit-frame-pointer -g -O1",
        }

    def verify_dynamically(self, finding: Finding,
                            trigger: Dict[str, Any],
                            context: Dict[str, Any]) -> Dict[str, Any]:
        results = {"confirmed": False, "ubsan_report": None}

        container_id = context.get("container_id")
        binary = context.get("ubsan_binary", "")
        if not container_id or not binary:
            return results

        from veriaudit.core.container_pool import ContainerPool
        pool = ContainerPool()

        for val in trigger.get("boundary_values", []):
            exit_code, stdout, stderr = pool.exec_cmd(
                container_id, f"echo {val} | {binary}", timeout=10,
            )
            if "signed integer overflow" in stderr or "runtime error" in stderr:
                results["confirmed"] = True
                results["ubsan_report"] = stderr[:500]
                results["trigger_value"] = val
                break

        return results


class FormatStringHandler(VulnerabilityClassHandler):
    """Handler for format string vulnerabilities (CWE-134)."""

    @property
    def vuln_class_name(self) -> str:
        return "format-string"

    @property
    def cwe_ids(self) -> List[str]:
        return ["CWE-134"]

    @property
    def applicable_languages(self) -> List[str]:
        return ["c++", "c"]

    def get_discovery_rules(self, language: str) -> List[Dict[str, Any]]:
        return [
            {"tool": "semgrep", "rule": "c-format-string"},
            {"tool": "codeql", "rule": "cpp/tainted-format-string"},
        ]

    def generate_trigger(self, finding: Finding,
                          context: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "trigger_type": "format_string_payloads",
            "vulnerability_type": "format-string",
            "payloads": [
                "%x%x%x%x", "%n%n%n%n", "%s%s%s%s",
                "%p%p%p%p", "AAAA%x%x%x%x%x%x%x%x",
            ],
        }

    def verify_dynamically(self, finding: Finding,
                            trigger: Dict[str, Any],
                            context: Dict[str, Any]) -> Dict[str, Any]:
        results = {"confirmed": False}

        container_id = context.get("container_id")
        binary = context.get("binary", "")
        if not container_id or not binary:
            return results

        from veriaudit.core.container_pool import ContainerPool
        pool = ContainerPool()

        for payload in trigger.get("payloads", []):
            exit_code, stdout, stderr = pool.exec_cmd(
                container_id, f"echo '{payload}' | {binary}", timeout=10,
            )
            # Format string crash is typically SIGSEGV
            if exit_code < 0 or "Segmentation fault" in stderr:
                results["confirmed"] = True
                results["crash_payload"] = payload
                break
            # Memory leak / info leak indicators
            if "%x" in payload and stdout and len(stdout) > 100:
                results["confirmed"] = True
                results["info_leak"] = True
                results["payload"] = payload
                break

        return results
